from building import *

cwd = GetCurrentDir()
src = []
CPPPATH = [cwd]

if GetDepend(['BSP_USING_SPI_FLASH']):
    src += ['spi_flash_init.c']

if GetDepend(['BSP_USING_USBD_FS']):
    src += ['usbd_fs_port.c']

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
